# Generated by Django 2.2.4 on 2020-10-23 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=200)),
                ('location_name', models.CharField(max_length=200)),
                ('whs_code', models.CharField(max_length=200)),
                ('whs_name', models.CharField(max_length=200)),
                ('loc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Location')),
                ('whs_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Warehouse')),
            ],
        ),
    ]
