# Generated by Django 2.2.4 on 2020-08-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cw_approved_date',
            field=models.CharField(blank=True, choices=[('80', 'Narrow'), ('medium', 'Medium'), ('wide', 'Wide')], default='80', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cw_condition_code',
            field=models.CharField(blank=True, choices=[('80', 'Narrow'), ('medium', 'Medium'), ('wide', 'Wide')], default='80', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cw_item_number',
            field=models.CharField(blank=True, choices=[('80', 'Narrow'), ('medium', 'Medium'), ('wide', 'Wide')], default='80', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cw_labor_cost',
            field=models.CharField(blank=True, choices=[('80', 'Narrow'), ('medium', 'Medium'), ('wide', 'Wide')], default='80', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cw_misc_cost',
            field=models.CharField(blank=True, choices=[('80', 'Narrow'), ('medium', 'Medium'), ('wide', 'Wide')], default='80', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cw_next_dlv_date',
            field=models.CharField(choices=[('80', 'Narrow'), ('medium', 'Medium'), ('wide', 'Wide')], default='80', max_length=200, null=True, verbose_name='Next Delivery Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cw_notes',
            field=models.CharField(blank=True, choices=[('80', 'Narrow'), ('medium', 'Medium'), ('wide', 'Wide')], default='80', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cw_parts_cost',
            field=models.CharField(blank=True, choices=[('80', 'Narrow'), ('medium', 'Medium'), ('wide', 'Wide')], default='80', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cw_quoted_date',
            field=models.CharField(blank=True, choices=[('80', 'Narrow'), ('medium', 'Medium'), ('wide', 'Wide')], default='80', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cw_vendor',
            field=models.CharField(blank=True, choices=[('80', 'Narrow'), ('medium', 'Medium'), ('wide', 'Wide')], default='80', max_length=200, null=True, verbose_name='Vendor'),
        ),
    ]
