# Generated by Django 2.2.4 on 2020-10-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_warehouselocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouselocation',
            name='bulk_imp_error',
            field=models.CharField(blank=True, default='', max_length=20000, null=True),
        ),
    ]
