# Generated by Django 2.2.4 on 2020-11-13 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('polls', '0002_location_visible_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(blank=True, choices=[('lowest_priority', 'Lowest Priority'), ('highest_priority', 'Highest Priority')], default='lowest_priority', max_length=40, null=True)),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
