# Generated by Django 2.2.4 on 2020-11-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_usergroupprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomProfile',
        ),
    ]
