# Generated by Django 2.2.4 on 2020-08-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_columnsettings_tmpl_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnsettings',
            name='width',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
