# Generated by Django 2.2.4 on 2020-10-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_warehouselocation_bulk_imp_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouselocation',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
