# Generated by Django 2.2.4 on 2020-08-24 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200821_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='arrival_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Arrival Date'),
        ),
        migrations.AddField(
            model_name='wostatus',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='columnsettings',
            name='width',
            field=models.FloatField(blank=True, default='', max_length=200, null=True),
        ),
    ]
