# Generated by Django 2.2.4 on 2020-12-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_customprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
