# Generated by Django 2.2.4 on 2020-09-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200826_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
