# Generated by Django 2.2.4 on 2021-02-10 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210126_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='loc_validated_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
