# Generated by Django 2.2.4 on 2021-03-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_wostatus_loc_validated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='int_rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
