# Generated by Django 2.2.4 on 2021-07-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_wostatus_int_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='print_length',
            field=models.FloatField(blank=True, default=8.5, max_length=200, null=True, verbose_name='Print Length'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='print_orientation',
            field=models.FloatField(blank=True, default=8.5, max_length=200, null=True, verbose_name='Print Orientation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='print_width',
            field=models.FloatField(blank=True, default=8.5, max_length=200, null=True, verbose_name='Print Width'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='printer_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Printer'),
        ),
    ]
