# Generated by Django 2.2.4 on 2020-09-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200908_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('conn_str', models.CharField(blank=True, max_length=200, null=True)),
                ('schema', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('secret', models.CharField(blank=True, max_length=200, null=True)),
                ('host', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=1521)),
                ('sid', models.CharField(max_length=200)),
                ('db_user', models.CharField(max_length=200)),
                ('db_pwd', models.CharField(max_length=200)),
                ('dj_user_id', models.IntegerField(default=0, verbose_name='Django auth user id.')),
            ],
        ),
    ]
