# Generated by Django 2.2.4 on 2021-08-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20210708_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlapps',
            name='app_type',
            field=models.CharField(blank=True, choices=[('operations', 'Operations'), ('management', 'Management'), ('imports', 'Imports')], default='operations', max_length=200, null=True),
        ),
    ]
