# Generated by Django 2.2.4 on 2021-08-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_mlapps_app_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='print_length',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='print_orientation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='print_width',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='printer_name',
        ),
        migrations.AddField(
            model_name='userappperms',
            name='print_length',
            field=models.FloatField(blank=True, default=8.5, max_length=200, null=True, verbose_name='Print Length'),
        ),
        migrations.AddField(
            model_name='userappperms',
            name='print_orientation',
            field=models.CharField(blank=True, choices=[('portait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=200, null=True, verbose_name='Print Orientation'),
        ),
        migrations.AddField(
            model_name='userappperms',
            name='print_tray',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Print Tray'),
        ),
        migrations.AddField(
            model_name='userappperms',
            name='print_width',
            field=models.FloatField(blank=True, default=8.5, max_length=200, null=True, verbose_name='Print Width'),
        ),
        migrations.AddField(
            model_name='userappperms',
            name='printer_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Printer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='computer_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='User@Computer ID'),
        ),
    ]
