# Generated by Django 2.2.4 on 2021-08-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210818_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='wostatus',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
