# Generated by Django 2.2.4 on 2020-09-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200911_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='airway_bill',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wostatus',
            name='pnm_modify',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
