# Generated by Django 2.2.4 on 2021-08-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20210823_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappperms',
            name='computer_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Computer ID'),
        ),
        migrations.AddField(
            model_name='userappperms',
            name='printnode_auth_key',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Print Node Auth Key'),
        ),
        migrations.AlterField(
            model_name='userappperms',
            name='print_length',
            field=models.FloatField(blank=True, default=11, max_length=200, null=True, verbose_name='Print Length'),
        ),
        migrations.AlterField(
            model_name='userappperms',
            name='print_tray',
            field=models.CharField(blank=True, default='1', max_length=200, null=True, verbose_name='Print Tray'),
        ),
    ]
