# Generated by Django 2.2.4 on 2020-09-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20200914_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='qty_reserved',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
