# Generated by Django 2.2.4 on 2021-09-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20210825_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='server_port',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='document',
            name='server_url',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='source_pk',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='document',
            name='source_table',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='url_path',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
