# Generated by Django 2.2.4 on 2020-09-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_wostatus_qty_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sysur_auto_key',
            field=models.IntegerField(blank=True, default='0', max_length=200, null=True, verbose_name='sysur_auto_key from Quantum'),
        ),
    ]
