# Generated by Django 2.2.4 on 2020-09-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_userprofile_sysur_auto_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sysur_auto_key',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='sysur_auto_key from Quantum'),
        ),
        migrations.AlterField(
            model_name='wostatus',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
