# Generated by Django 2.2.4 on 2021-09-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20210906_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlapps',
            name='app_type',
            field=models.CharField(blank=True, choices=[('operations', 'Operations'), ('management', 'Management'), ('imports', 'Imports'), ('exports', 'Exports')], default='operations', max_length=200, null=True),
        ),
    ]
