# Generated by Django 2.2.4 on 2020-09-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20200918_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='dpt_auto_key',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
