# Generated by Django 2.2.4 on 2021-09-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20210906_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='vendor_key',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
