# Generated by Django 2.2.4 on 2021-09-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_wostatus_vendor_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_extension',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_key',
            field=models.IntegerField(default=1),
        ),
    ]
