# Generated by Django 2.2.4 on 2021-11-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20210930_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='si_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
