# Generated by Django 2.2.4 on 2021-11-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_wostatus_si_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='cart',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
