# Generated by Django 2.2.4 on 2020-09-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_wostatus_next_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='cmp_auto_key',
            field=models.IntegerField(default=0),
        ),
    ]
