# Generated by Django 2.2.4 on 2021-12-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_wostatus_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroupprofile',
            name='conn_string',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Phone Home Connection String'),
        ),
        migrations.AddField(
            model_name='usergroupprofile',
            name='quantum_cmp_key',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Quantum Company Key'),
        ),
    ]
