# Generated by Django 2.2.4 on 2021-12-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20211209_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlapps',
            name='app_type',
            field=models.CharField(blank=True, choices=[('operations', 'Operations'), ('management', 'Management'), ('setup', 'Setup'), ('exports', 'Exports')], default='operations', max_length=200, null=True),
        ),
    ]
