# Generated by Django 2.2.4 on 2021-12-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20211214_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('soh_auto_key', models.IntegerField(blank=True, default=0, null=True)),
                ('cmp_auto_key', models.IntegerField(default=0)),
                ('spn_auto_key', models.IntegerField(default=0)),
                ('spn_code', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('part_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('priority', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
