# Generated by Django 2.2.4 on 2021-12-20 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
