# Generated by Django 2.2.4 on 2022-01-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20220103_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlapps',
            name='app_type',
            field=models.CharField(blank=True, choices=[('operations', 'Operations'), ('management', 'Management'), ('dashboards', 'Dashboards'), ('setup', 'Setup'), ('exports', 'Exports')], default='operations', max_length=200, null=True),
        ),
    ]
