# Generated by Django 2.2.4 on 2022-01-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20220103_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='qty_available',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wostatus',
            name='qty_needed',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
