# Generated by Django 2.2.4 on 2022-01-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20220107_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('batch_id', models.IntegerField(blank=True, default='0', max_length=200, null=True)),
                ('sysur_auto_key', models.IntegerField(blank=True, default='0', max_length=200, null=True)),
            ],
        ),
    ]
