# Generated by Django 2.2.4 on 2022-01-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_laborbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborbatch',
            name='batch_id',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='laborbatch',
            name='sysur_auto_key',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
