# Generated by Django 2.2.4 on 2022-02-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20220201_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wotask',
            name='wot_labor_hours',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
