# Generated by Django 2.2.4 on 2022-03-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20220208_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborbatch',
            name='batch_id',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
