# Generated by Django 2.2.4 on 2022-04-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_auto_20220419_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappperms',
            name='print_orientation',
            field=models.CharField(blank=True, choices=[('portait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=200, null=True, verbose_name='Print Orientation'),
        ),
    ]
