# Generated by Django 2.2.4 on 2022-04-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_auto_20220419_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userappperms',
            name='print_orientation',
        ),
    ]
