# Generated by Django 2.2.4 on 2022-04-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_remove_userappperms_print_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='wob_auto_key',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
