# Generated by Django 2.2.4 on 2022-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_wostatus_wob_auto_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='consignment_code',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wostatus',
            name='qty_oh',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
