# Generated by Django 2.2.4 on 2022-05-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_auto_20220510_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wostatus',
            name='att_name',
        ),
        migrations.RemoveField(
            model_name='wostatus',
            name='att_value',
        ),
    ]
