# Generated by Django 2.2.4 on 2022-05-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_auto_20220510_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefatts',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
