# Generated by Django 2.2.4 on 2022-05-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_userdefatts_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='pnm_auto_key',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
