# Generated by Django 2.2.4 on 2022-05-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_wostatus_pnm_auto_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefatts',
            name='auto_key',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
