# Generated by Django 2.2.4 on 2022-05-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_userdefatts_auto_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefatts',
            name='activity',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
