# Generated by Django 2.2.4 on 2022-05-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_wostatus_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefatts',
            name='att_seq',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
