# Generated by Django 2.2.4 on 2022-06-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_userdefatts_att_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='wotask',
            name='wtm_auto_key',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
