# Generated by Django 2.2.4 on 2022-06-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_wotask_wtm_auto_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='alt_avail',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
