# Generated by Django 2.2.4 on 2022-08-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0054_consignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wotask',
            name='wot_sequence',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
