# Generated by Django 2.2.4 on 2022-10-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0058_partnumbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnumbers',
            name='pnm_auto_key',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
