# Generated by Django 2.2.4 on 2022-10-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0059_partnumbers_pnm_auto_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='partconditions',
            name='activity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
