# Generated by Django 2.2.4 on 2022-10-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0060_partconditions_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partconditions',
            name='activity',
        ),
    ]
