# Generated by Django 2.2.4 on 2022-10-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0063_auto_20221013_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kiosk_apps',
            field=models.ManyToManyField(to='polls.MLApps'),
        ),
    ]
