# Generated by Django 2.2.4 on 2022-11-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0064_userprofile_kiosk_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='kiosk_apps',
            field=models.ManyToManyField(blank=True, null=True, to='polls.MLApps'),
        ),
    ]
