# Generated by Django 2.2.4 on 2022-11-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0066_auto_20221104_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='cond_level_gsix',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wostatus',
            name='cond_level_zero',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
