# Generated by Django 2.2.4 on 2022-12-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0068_wostatus_status_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wostatus',
            name='status_type',
        ),
        migrations.AddField(
            model_name='wotask',
            name='status_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
