# Generated by Django 2.2.4 on 2023-01-23 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0069_auto_20221212_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLabor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('wo_number', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('sequence', models.IntegerField(blank=True, default='0', null=True)),
                ('task_name', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('task_desc', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('pn', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('part_desc', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('sysur_auto_key', models.IntegerField(blank=True, default='0', null=True)),
                ('entry_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('hours', models.FloatField(blank=True, default='0.00', null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_approved_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_batch_no',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_condition_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_ctrl_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_ctrl_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_cust_ref_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_customer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_due_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_due_date_var',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_entry_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_gate_1_text',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_gate_2_text',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_gate_3_text',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_gate_4_text',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_gate_qty',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_item_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_labor_cost',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_location_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_manager',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_misc_cost',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_next_dlv_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_notes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_parent_wo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_part_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_parts_cost',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_quantity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_quoted_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_rack',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_rank',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_serial_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_stock_line',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_stock_owner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_sub_wo_gate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_time_loc',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_time_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_total_cost',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_update_stamp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_vendor',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_wh_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_wo_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_wo_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_wot_description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_wot_labor_hours',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_wot_labor_last',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_wot_sequence',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_wot_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cw_wot_technician',
        ),
    ]
