# Generated by Django 2.2.4 on 2023-01-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0070_auto_20230123_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklabor',
            name='sysur_auto_key',
        ),
        migrations.AddField(
            model_name='tasklabor',
            name='user_name',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
