# Generated by Django 2.2.4 on 2023-02-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0071_auto_20230123_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroupprofile',
            name='private_key',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Private Key'),
        ),
    ]
