# Generated by Django 2.2.4 on 2023-02-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0072_usergroupprofile_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroupprofile',
            name='public_key',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Public Key'),
        ),
    ]
