# Generated by Django 2.2.4 on 2023-02-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0073_usergroupprofile_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroupprofile',
            name='private_key',
            field=models.TextField(blank=True, default='', max_length=300, null=True, verbose_name='Private Key'),
        ),
        migrations.AlterField(
            model_name='usergroupprofile',
            name='public_key',
            field=models.TextField(blank=True, default='', max_length=300, null=True, verbose_name='Public Key'),
        ),
    ]
