# Generated by Django 2.2.4 on 2023-02-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0074_auto_20230208_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklabor',
            name='wot_auto_key',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
