# Generated by Django 2.2.4 on 2023-03-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0079_auto_20230301_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlapps',
            name='print_enabled',
            field=models.BooleanField(default=False, verbose_name='Print Enabled'),
        ),
    ]
