# Generated by Django 2.2.4 on 2023-04-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0083_auto_20230411_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='op_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='operation',
            name='part_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='operation',
            name='part_number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
