# Generated by Django 2.2.4 on 2023-05-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0084_auto_20230411_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='spn_code',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
