# Generated by Django 2.2.4 on 2023-06-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201026_2221'),
        ('polls', '0020_wostatus_cmp_auto_key'),
        ('polls', '0085_wostatus_spn_code'),
    ]

    operations = [
    ]
