# Generated by Django 2.2.4 on 2023-07-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0086_merge_20230612_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusselection',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
