# Generated by Django 4.2.4 on 2024-03-01 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0091_taskskills_remove_userprofile_computer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pilogs',
            name='stm_auto_key',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statusselection',
            name='text_wos',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userquapirel',
            name='sysur_auto_key',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='sysur_auto_key from Quantum'),
        ),
        migrations.AddField(
            model_name='wostatus',
            name='closed_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='wostatus',
            name='due_date_var',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wostatus',
            name='update_stamp',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
