# Generated by Django 4.2.4 on 2024-04-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0093_tasklabor_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wotask',
            name='ac_model',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wotask',
            name='ac_reg',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wotask',
            name='ac_sn',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wotask',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wotask',
            name='esn',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wotask',
            name='part_description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
