# Generated by Django 4.2.4 on 2024-10-14 18:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0095_wotask_eng_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('rct_auto_key', models.IntegerField(blank=True, default=0, null=True)),
                ('categ_code', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=2000000)),
                ('trigger_sql', models.CharField(default='', max_length=2000000)),
                ('quantum_table', models.CharField(default='', max_length=2200000)),
            ],
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=2000000)),
                ('trigger_sql', models.CharField(default='', max_length=2000000, null=True)),
                ('quantum_table', models.CharField(default='', max_length=2200000, null=True)),
                ('wo_number', models.CharField(default='', max_length=2000000, null=True)),
                ('pn', models.CharField(default='', max_length=2000000, null=True)),
                ('task', models.CharField(default='', max_length=2200000, null=True)),
                ('emp_name', models.CharField(default='', max_length=2200000, null=True)),
                ('cond_code', models.CharField(default='', max_length=2200000, null=True)),
                ('quantity', models.FloatField(blank=True, default=0, null=True)),
                ('audit_trail_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.audittrail')),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.eventmanager')),
            ],
        ),
        migrations.CreateModel(
            name='MailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('to_emails', models.CharField(default='', max_length=2000000, null=True)),
                ('from_email', models.CharField(default='', max_length=2000000, null=True)),
                ('cc_field', models.CharField(default='', max_length=2000000, null=True)),
                ('text_fields', models.CharField(default='', max_length=2000000, null=True)),
                ('active', models.CharField(default='green-check.png', max_length=2000000)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipVia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('svc_auto_key', models.IntegerField(blank=True, default=0, null=True)),
                ('ship_via_code', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='partconditions',
            name='pcc_auto_key',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partnumbers',
            name='mfg_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='num_apps',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Number of Apps'),
        ),
        migrations.AddField(
            model_name='wostatus',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='wostatus',
            name='uom_code',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='wotask',
            name='wot_auto_text',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='MailMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(default='', max_length=2000000)),
                ('body', models.CharField(default='', max_length=2000000)),
                ('body_html', models.CharField(default='', max_length=2000000)),
                ('to_emails', models.CharField(default='', max_length=2000000)),
                ('cc_field', models.CharField(default='', max_length=2000000)),
                ('from_email', models.CharField(default='', max_length=2000000)),
                ('status', models.CharField(blank=True, choices=[('sent', 'Success'), ('failure', 'Failure'), ('draft', 'Draft')], default='draft', max_length=20, null=True)),
                ('event_note_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.eventnotification')),
                ('mail_group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.mailgroup')),
            ],
        ),
        migrations.AddField(
            model_name='eventnotification',
            name='mail_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.mailgroup'),
        ),
        migrations.AddField(
            model_name='eventnotification',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventmanager',
            name='mail_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.mailgroup'),
        ),
        migrations.AddField(
            model_name='eventmanager',
            name='ml_apps_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.mlapps'),
        ),
    ]
