# Generated by Django 5.0.3 on 2025-12-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PIUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('stock_label', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('control_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('control_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='Control ID')),
            ],
        ),
        migrations.CreateModel(
            name='QCUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('user_auto_key', models.IntegerField(default=0, verbose_name='User Key from Quantum DB')),
                ('pass_key', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('employee_code', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
