# Generated by Django 2.2.4 on 2020-03-06 15:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('uri', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='MoTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opm_auto_key', models.IntegerField(default='', verbose_name='OPM AUTO KEY')),
                ('msg', models.CharField(default='', max_length=6000)),
                ('mo_number', models.CharField(default='', max_length=200)),
                ('is_debug', models.BooleanField(verbose_name='Debug On')),
                ('host', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=1521)),
                ('sid', models.CharField(max_length=200)),
                ('db_user', models.CharField(max_length=200)),
                ('db_pwd', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PILogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(default='', max_length=200)),
                ('quantity', models.FloatField(default=0)),
                ('stock_label', models.CharField(default='', max_length=200)),
                ('ctrl_number', models.CharField(default='', max_length=200)),
                ('ctrl_id', models.CharField(default='', max_length=200)),
                ('location_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('user_id', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuantumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='None', max_length=200, null=True, verbose_name='USER_ID from SYS_USERS table in QCTL.')),
                ('user_auto_key', models.IntegerField(default=0, verbose_name='User Key from Quantum DB')),
                ('pass_key', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('employee_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('dj_user_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='Django auth user id.')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='StatusSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wos_auto_key', models.IntegerField(default=0)),
                ('severity', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('is_dashboard', models.BooleanField(default=1, verbose_name='Is Dashboard')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrolive.QuantumUser')),
            ],
        ),
        migrations.CreateModel(
            name='WOStatusConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=1521)),
                ('sid', models.CharField(max_length=200)),
                ('db_user', models.CharField(max_length=200)),
                ('db_pwd', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WOStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('woo_auto_key', models.IntegerField(blank=True, default=0, null=True)),
                ('stm_auto_key', models.IntegerField(blank=True, default=0, null=True)),
                ('wos_auto_key', models.IntegerField(blank=True, default=0, null=True)),
                ('supdate_msg', models.CharField(blank=True, default='', max_length=6000, null=True)),
                ('time_status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('due_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('entry_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('stock_line', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('part_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('serial_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('location_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('wh_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('time_loc', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('user_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('need_date_variance', models.IntegerField(blank=True, default=0, null=True)),
                ('due_date_var', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('update_stamp', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('customer', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('manager', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('rank', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('wo_type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cust_ref_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('is_dashboard', models.BooleanField(blank=True, default=1, null=True)),
                ('is_racking', models.BooleanField(blank=True, default=0, null=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('rack', models.CharField(blank=True, default='none set', max_length=200, null=True)),
                ('ctrl_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ctrl_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('status_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrolive.StatusSelection')),
            ],
        ),
        migrations.CreateModel(
            name='UserAppPerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_access', models.BooleanField(default=True, verbose_name='Global Access')),
                ('ml_apps_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrolive.MLApps')),
                ('reg_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrolive.QuantumUser')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrolive.Question')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('field_changed', models.CharField(default='', max_length=200)),
                ('new_val', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=2200)),
                ('user_code', models.CharField(default='', max_length=200)),
                ('ml_apps_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrolive.MLApps')),
            ],
        ),
        migrations.CreateModel(
            name='AppModes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('ml_apps_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrolive.MLApps')),
            ],
        ),
    ]
