# Generated by Django 2.2.4 on 2020-03-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrolive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audittrail',
            old_name='user_code',
            new_name='user_id',
        ),
    ]
