# Generated by Django 2.2.4 on 2020-03-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrolive', '0003_auto_20200306_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='wostatus',
            name='parent_wo',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
